import './globals.css';
import { Kumbh_Sans } from 'next/font/google';

const kumbhSans = Kumbh_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'E-commerce Product Page',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon-32x32.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>{children}</body>
    </html>
  );
}
